---
title: "R Notebook"
output: html_notebook
---
```{r}
library(tidyverse)
library(MCMC.qpcr)
```

```{r}
poa <- read.csv("~/Documents/projects/socs-brains/POA_mcmcqpcr_ready.csv")
pvn <- read.csv("~/Documents/projects/socs-brains/PVN_mcmcqpcr_ready.csv")
key <-read.csv("~/Desktop/PRLvsHPG_sample_key.csv")
effic <-read.csv("~/Documents/projects/socs-brains/socs_efficiencies.csv")
```

```{r}
#join sample keys with qPCR data 
poa_join <-
inner_join(poa, key, by = c("bird_id" = "band_no")) %>%
  select(-nest_no, -dosage_group) %>%
  select(bird_id, treatment, sex, everything())


pvn_join <-
inner_join(poa, key, by = c("bird_id" = "band_no")) %>%
  select(-nest_no, -dosage_group) %>%
  select(bird_id, treatment, sex, everything())
```

```{r}
#check references
poa_join$treatment <-relevel(poa_join$treatment, ref = "vehicle")
poa_join$sex <-relevel(poa_join$sex, ref = "m")


pvn_join$treatment <-relevel(pvn_join$treatment, ref = "vehicle")
pvn_join$sex <-relevel(pvn_join$sex, ref = "m")

```

```{r}
#PVN

colnames(pvn_join)[1] <- "sample"
qs <- cq2counts(data = pvn_join, effic = effic, genecols = c(4:8), condcols = c(1:3)) 

colnames(pvn_join)

naive2 <- mcmc.qpcr(data = qs, fixed = "treatment+sex")
summary(naive2)

HPDsummary(model = naive2, data = qs, relative = TRUE)

#soft normalization to gapdh and hprt1
soft_norm <- mcmc.qpcr(
fixed="treatment",
random="sample",
data=qs,
controls=c("gapdh","hprt1"),
normalize=TRUE
)
smm.norms <- HPDsummary(soft_norm,qs,relative=F)
summary(soft_norm)

#informing about control genes 
informed <- mcmc.qpcr(
fixed="treatment",
random="sample",
data=qs,
controls=c("gapdh","hprt1"),
m.fix=1.2
)

new.norms <- HPDsummary(informed,qs,relative=F)
summary(informed)

```






